### ISSUE TITLE
update hex package to use Timex 2.0

### ISSUE THREAD

**Issue by kenta-polyglot** [bryanjos/aws_auth#15]
Hi, I think you should update your hex package to use Timex 2.0.

Your mix.exs in master branch is like below:

```
  defp deps do
    [{:timex, "~> 2.0"}]
  end
```

But mix.exs in your newest hex package is like below:

```
  defp deps do
    [{:timex, "~> 1.0"}]
  end
```

I think you uploaded old source code to hex.pm.

**Comment by bryanjos** [comment]
updated: https://hex.pm/packages/aws_auth
