### ISSUE TITLE
Support for queries containing ':' and '/'. Support for queries without payloads.

### ISSUE THREAD

**Issue by adenisonafifi** [bryanjos/aws_auth#16]
The query parameters aren't encoded as stated in the requirements 

> http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
> URI-encode each parameter name and value according to the following rules:
> 
> Do not URI-encode any of the unreserved characters that RFC 3986 defines: A-Z, a-z, 0-9, hyphen ( - ), underscore ( _ ), period ( . ), and tilde ( ~ ).
> Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do) and extended UTF-8 characters must be in the form %XY%ZA%BC.

Also, if there is no payload the hashed payload should not be: "UNSIGNED-PAYLOAD". 

> If the payload is empty, use an empty string as the input to the hash function. In the IAM example, the payload is empty.
> Example hashed payload (empty string)
> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

I'm not sure if this library is intended to be used with s3 only, but in order to sign SNS queries I needed to make those changes. Thank you for publishing this library!

**Comment by bryanjos** [comment]
Got it. I haven't done much work on this in a while, but I can update it when I get some free time or accept any PRs.

**Comment by kenta-aktsk** [comment]
Hi, I just sent pull request.
I tested it against s3 and AWS Elasticsearch service.

**Comment by bryanjos** [comment]
@adenisonafifi I just published version 0.4.0 which should resolve the first issue along with the changes that @kenta-aktsk made that should resolve the second issue 

https://hex.pm/packages/aws_auth
