### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by benwilson512** [bryanjos/aws_auth#2]
Hey, would you mind tagging the releases you have on hex.pm as releases here as well? Right now there isn't any easy way (other than by date) to determine what ref the package on hex is at.

Thanks!

**Comment by bryanjos** [comment]
Yeah I can do that. I used to do it and then I stopped for whatever reason. I'll start with the next release. I haven't given this library much love and then I found out about erl_cloud.

**Comment by benwilson512** [comment]
Thanks no worries, erl_cloud is definitely handy.
