### ISSUE TITLE
Do you support direct from Browser POST's

### ISSUE THREAD

**Issue by simonh1000** [bryanjos/aws_auth#21]
I was looking at how I could emulate http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html with your library

**Comment by bryanjos** [comment]
So I never really got around to trying it, but that was the original goal. If it is something that is a priority, I have in an app I'm working on used ex_aws to create browser POST urls using [presigned_url](https://hexdocs.pm/ex_aws/ExAws.S3.Client.html#c:presigned_url/4)

**Comment by simonh1000** [comment]
I'll take a look at this, but in the mean time I've been forced to retreat from pre-signed urls while I work out how to manipulate multi-part forms in Elm

**Comment by swennemans** [comment]
@bryanjos interesting. How would you use the `presigned_url` function with specific headers that need to be signed?

**Comment by andshape** [comment]
@bryanjos Could you please provide a code sample of how you got it to work using the presigned_url function from ex_aws? 
Thanks!

**Comment by bryanjos** [comment]
Keep in mind I was using ex_aws 0.5 so for a complete setup you should check the docs at that version. With that, after creating the module that uses `ExAws.S3.Client`

``` elixir
defmodule MyApp.S3 do
  use ExAws.S3.Client, otp_app: :my_app
end
```

You can get a presigned url with the following

``` elixir
{:ok, signed_url} =MyApp.S3.presigned_url(:put, "mybucket", "mykey.txt")
```

From the linked issue on ex_aws looks like some work is going into improving that functionality
