### ISSUE TITLE
Possible breaking change in 0.6.4

### ISSUE THREAD

**Issue by radar** [bryanjos/aws_auth#30]
See comment thread here: https://github.com/bryanjos/aws_auth/commit/1e8944de3c41780dc392cab035ff5494ce35fdab

@cdegroot: Let us continue our conversation here.

@cdegroot provided this script to attempt to reproduce the issue:

```elixir
method = :get
url = "http://foo.bar/lol"
headers = [host: "foo.bar"]
body = "This is some body stuff"
access_key_id = "1234"
secret_access_key = "abcdef"
region = "us-west-2"

aws_config = %{}
  |> Map.put(:access_key_id, access_key_id)
  |> Map.put(:secret_access_key, secret_access_key)
  |> Map.put(:region, region)
  |> Map.put(:enabled, true)
Application.put_env(:elastic, :aws, aws_config)

IO.inspect Elastic.AWS.sign_authorization_headers(method, url, headers, body)
```

This script fails because the `sign_authorization_headers` function is not defined here. I think @cdegroot meant `sign_url`, so I amended the script to do that.

```
method = :get
url = "http://foo.bar/lol"
headers = [host: "foo.bar"]
body = "This is some body stuff"
access_key_id = "1234"
secret_access_key = "abcdef"
region = "us-west-2"

aws_config = %{}
  |> Map.put(:access_key_id, access_key_id)
  |> Map.put(:secret_access_key, secret_access_key)
  |> Map.put(:region, region)
  |> Map.put(:enabled, true)
Application.put_env(:elastic, :aws, aws_config)

IO.inspect Elastic.AWS.sign_url(method, url, headers, body)
```

I then attempted to run this under the [elastic](https://github.com/radar/elastic) repo, checked out to current master (radar/elastic@eca120b31572aa5d8b5b3990e8d68dc96efeb3f4).  The current master has aws_auth locked to 0.6.2.

I then ran this script using `mix run repro.exs`, and got the following output:

```
"http://foo.bar/lol?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1234%2F20170613%2Fus-west-2%2Fes%2Faws4_request&X-Amz-Date=20170613T032051Z&X-Amz-Expires=86400&X-Amz-Signature=ca0745177024aa6cfc985d629d2b92a8dba9854b9de5572d3d27d5a2fb3c9e7a&X-Amz-SignedHeaders=host"
```

Then I bumped the dependency to 0.6.4 by running `mix deps.update aws_auth`. I then ensured this dependency was indeed updated by running `mix deps`:

```
* aws_auth (Hex package) (mix)
  locked at 0.6.4 (aws_auth) 4ecd73cb
```

Then I ran the script again, using the same command (`mix run repro.exs`) and I still see the same output:

```
"http://foo.bar/lol?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1234%2F20170613%2Fus-west-2%2Fes%2Faws4_request&X-Amz-Date=20170613T032223Z&X-Amz-Expires=86400&X-Amz-Signature=20849cbf7b66598caa57f1a9255b08431780e12a979ba4b5b881f2045488fdb5&X-Amz-SignedHeaders=host"
```

I would like @cdegroot to provide steps -- similar to mine -- to show an issue here. I am unable to reproduce it, but I would still like to investigate it as he claims to be seeing _something_.

**Comment by cdegroot** [comment]
Ah - check. We have - for reasons I still need to dive into - forked `elastic` (PRs forthcoming - a couple of additional methods and one patch which probably will see more debate which is exactly revolving around signing). Let's try not to step into that debate here and focus on the API compatbility issue. Our forked code has [a slightly different signing method](https://github.com/PagerDuty/elastic/blob/use-header-based-auth-for-aws/lib/elastic/aws.ex#L22) where we call into aws_auth [here](https://github.com/PagerDuty/elastic/blob/use-header-based-auth-for-aws/lib/elastic/aws.ex#L32). Apologies for not realizing that this method only exists in our forked version.

**Comment by radar** [comment]
No problems @cdegroot. If you have any further issues please open them here with steps to reproduce.
