### ISSUE TITLE
Auth fails when glob pattern is used

### ISSUE THREAD

**Issue by matrinox** [bryanjos/aws_auth#33]
Using the example on the page...
```elixir
AWSAuth.sign_url("AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
  "GET",
  "https://examplebucket.s3.amazonaws.com/*",
  "us-east-1",
  "s3",
  Map.new,
  ~N[2013-05-24 00:00:00])
```

This fails. The exact one I tested was using AWS elasticsearch service but I'm sure it's the same here

**Comment by radar** [comment]
Hi, thanks for letting us know.

Which page do you mean?

**Comment by matrinox** [comment]
Oh sorry, I wasn't very clear. I meant that I used the example on the page and modified it to show one with a glob pattern, i.e. asterisk.

The encoding is not correct for the URL. I'm looking into fixing it and will link a PR soon

**Comment by radar** [comment]
Thanks @matrinox. A PR would be really great :) Looking forward to it.
