### ISSUE TITLE
Trailing Slashes on the URL break signature

### ISSUE THREAD

**Issue by bravely** [bryanjos/aws_auth#36]
Just spent an afternoon debugging this, and AWS' return error just says their calculated signature is different than my own.

Considering an ending `/` on a URL is often inserted, I feel like the library standardizing this would help ease of use.

**Comment by radar** [comment]
Thanks for letting us know!

Would you mind submitting a PR to fix this for us?

**Comment by bravely** [comment]
I think I'm gonna try to do that in the coming days, just wanted to file an issue to both keep track and notify any others who face a similar issue.
